import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main> {children} </main>
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
